---
- name: Check if PostgreSQL is already installed
  command: psql --version
  register: psql_check
  ignore_errors: true
  changed_when: false

- name: Check if PostgreSQL service is active
  command: systemctl status postgresql
  register: postgresql_service_check
  ignore_errors: true
  changed_when: false

- name: Check if PostgreSQL data directory exists
  stat:
    path: /var/lib/pgsql/data/postgresql.conf
  register: postgresql_data_check
  become: true

- name: Install PostgreSQL packages
  dnf:
    name:
      - postgresql
      - postgresql-server
      - postgresql-contrib
      - python3-psycopg2
    state: present
  become: true
  when: psql_check.rc != 0

- name: Initialize PostgreSQL database
  command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/postgresql.conf
  become: true
  when:
    - not postgresql_data_check.stat.exists
    - postgresql_service_check.rc != 0

- name: Start PostgreSQL service
  systemd:
    name: postgresql
    state: started
  become: true
  when: postgresql_service_check.rc != 0

- name: Enable PostgreSQL service
  systemd:
    name: postgresql
    enabled: true
  become: true
  when: postgresql_service_check.rc != 0

- name: Get PostgreSQL version
  shell: psql --version | cut -d " " -f 3
  register: postgres_version
  changed_when: false
  when: psql_check.rc == 0

- name: Display PostgreSQL version
  debug:
    msg: "PostgreSQL version {{ postgres_version.stdout_lines }} is installed"
  when: postgres_version is defined
