---
  - name: Ensure Redis repository is enabled
    ansible.builtin.dnf:
      name: redis
      state: present
      update_cache: yes
    become: yes

  - name: Install Redis
    ansible.builtin.dnf:
      name: redis
      state: latest
    become: yes

  - name: Ensure Redis is enabled and started
    ansible.builtin.systemd:
      name: redis
      enabled: yes
      state: started
    become: yes
