---
- name: Get current user's home directory
  set_fact:
    user_home: "{{ ansible_env.HOME }}"

- name: Install curl (needed for Poetry installer)
  dnf:
    name: curl
    state: present
  become: true

- name: Download Poetry installer
  get_url:
    url: https://install.python-poetry.org
    dest: /tmp/install-poetry.py
    mode: '0755'

- name: Install Poetry using the official installer
  shell: |
    export PYENV_ROOT="{{ user_home }}/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
    curl -sSL https://install.python-poetry.org | python3 -
  args:
    executable: /bin/bash
    creates: "{{ user_home }}/.local/bin/poetry"

- name: Add Poetry to user's .bashrc
  blockinfile:
    path: "{{ user_home }}/.bashrc"
    block: |
      # Poetry
      export PATH="$HOME/.local/bin:$PATH"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - POETRY"
    create: yes

- name: Configure Poetry to create virtualenvs in project directories
  shell: |
    export PATH="{{ user_home }}/.local/bin:$PATH"
    poetry config virtualenvs.in-project true
  args:
    executable: /bin/bash
