---
- name: Ensure system packages are up-to-date
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Install unzip (required to extract AWS CLI)
  dnf:
    name: unzip
    state: present

- name: Download AWS CLI v2
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: /tmp/awscliv2.zip

- name: Unzip AWS CLI package
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/
    remote_src: yes

- name: Install AWS CLI
  command: /tmp/aws/install

- name: Verify AWS CLI installation
  command: aws --version
