---
  - name: Ensure system packages are up-to-date
    dnf:
      name: "*"
      state: latest
      update_cache: yes
      exclude: lksctp-tools.i686

  - name: Install unzip and gnupg (required for AWS CLI and PGP verification)
    dnf:
      name:
        - unzip
        - gnupg
      state: present

  - name: Download AWS CLI v2
    get_url:
      url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
      dest: /tmp/awscliv2.zip

  - name: Download AWS CLI signature file
    get_url:
      url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip.sig"
      dest: /tmp/awscliv2.sig

  - name: Create AWS CLI PGP public key file
    copy:
      content: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        mQINBF2Cr7UBEADJZHcgusOJl7ENSyumXh85z0TRV0xJorM2B/JL0kHOyigQluUG
        ZMLhENaG0bYatdrKP+3H91lvK050pXwnO/R7fB/FSTouki4ciIx5OuLlnJZIxSzx
        PqGl0mkxImLNbGWoi6Lto0LYxqHN2iQtzlwTVmq9733zd3XfcXrZ3+LblHAgEt5G
        TfNxEKJ8soPLyWmwDH6HWCnjZ/aIQRBTIQ05uVeEoYxSh6wOai7ss/KveoSNBbYz
        gbdzoqI2Y8cgH2nbfgp3DSasaLZEdCSsIsK1u05CinE7k2qZ7KgKAUIcT/cR/grk
        C6VwsnDU0OUCideXcQ8WeHutqvgZH1JgKDbznoIzeQHJD238GEu+eKhRHcz8/jeG
        94zkcgJOz3KbZGYMiTh277Fvj9zzvZsbMBCedV1BTg3TqgvdX4bdkhf5cH+7NtWO
        lrFj6UwAsGukBTAOxC0l/dnSmZhJ7Z1KmEWilro/gOrjtOxqRQutlIqG22TaqoPG
        fYVN+en3Zwbt97kcgZDwqbuykNt64oZWc4XKCa3mprEGC3IbJTBFqglXmZ7l9ywG
        EEUJYOlb2XrSuPWml39beWdKM8kzr1OjnlOm6+lpTRCBfo0wa9F8YZRhHPAkwKkX
        XDeOGpWRj4ohOx0d2GWkyV5xyN14p2tQOCdOODmz80yUTgRpPVQUtOEhXQARAQAB
        tCFBV1MgQ0xJIFRlYW0gPGF3cy1jbGlAYW1hem9uLmNvbT6JAlQEEwEIAD4CGwMF
        CwkIBwIGFQoJCAsCBBYCAwECHgECF4AWIQT7Xbd/1cEYuAURraimMQrMRnJHXAUC
        ZqFYbwUJCv/cOgAKCRCmMQrMRnJHXKYuEAC+wtZ611qQtOl0t5spM9SWZuszbcyA
        0xBAJq2pncnp6wdCOkuAPu4/R3UCIoD2C49MkLj9Y0Yvue8CCF6OIJ8L+fKBv2DI
        yWZGmHL0p9wa/X8NCKQrKxK1gq5PuCzi3f3SqwfbZuZGeK/ubnmtttWXpUtuU/Iz
        VR0u/0sAy3j4uTGKh2cX7XnZbSqgJhUk9H324mIJiSwzvw1Ker6xtH/LwdBeJCck
        bVBdh3LZis4zuD4IZeBO1vRvjot3Oq4xadUv5RSPATg7T1kivrtLCnwvqc6L4LnF
        0OkNysk94L3LQSHyQW2kQS1cVwr+yGUSiSp+VvMbAobAapmMJWP6e/dKyAUGIX6+
        2waLdbBs2U7MXznx/2ayCLPH7qCY9cenbdj5JhG9ibVvFWqqhSo22B/URQE/CMrG
        +3xXwtHEBoMyWEATr1tWwn2yyQGbkUGANneSDFiTFeoQvKNyyCFTFO1F2XKCcuDs
        19nj34PE2TJilTG2QRlMr4D0NgwLLAMg2Los1CK6nXWnImYHKuaKS9LVaCoC8vu7
        IRBik1NX6SjrQnftk0M9dY+s0ZbAN1gbdjZ8H3qlbl/4TxMdr87m8LP4FZIIo261
        Eycv34pVkCePZiP+dgamEiQJ7IL4ZArio9mv6HbDGV6mLY45+l6/0EzCwkI5IyIf
        BfWC9s/USgxchg==
        =ptgS
        -----END PGP PUBLIC KEY BLOCK-----
      dest: /tmp/aws-cli-public-key.asc

  - name: Import AWS CLI PGP public key
    command: gpg --import /tmp/aws-cli-public-key.asc

  - name: Verify AWS CLI zip file signature
    command: gpg --verify /tmp/awscliv2.sig /tmp/awscliv2.zip

  - name: Unzip AWS CLI package
    unarchive:
      src: /tmp/awscliv2.zip
      dest: /tmp/
      remote_src: yes

  - name: Install AWS CLI
    command: /tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update

  - name: Verify AWS CLI installation
    command: aws --version

  # Clean up installation files

  - name: Clean up AWS CLI installation files
    file:
      path: "/tmp/awscliv2.zip"
      state: absent

  - name: Remove unarchived AWS installation folder
    file:
      path: "/tmp/aws"
      state: absent

  - name: Remove AWS CLI public key file
    file:
      path: "/tmp/aws-cli-public-key.asc"
      state: absent

  - name: Remove AWS CLI signature file
    file:
      path: "/tmp/awscliv2.sig"
      state: absent

  - name: Configure AWS CLI using environment variables
    command: aws configure set aws_access_key_id {{ aws_access_key_id }}

  - name: Configure AWS CLI secret access key using environment variables
    command: aws configure set aws_secret_access_key {{  aws_secret_access_key }}

  - name: Configure AWS CLI default region using environment variables
    command: aws configure set region {{  aws_secret_access_key }}

  - name: Configure AWS CLI default output using environment variables
    command: aws configure set region {{  aws_default_output }}
