---
- name: Setup AJF Fedora Workstation
  hosts: all
  roles:
    - { role: aws-cli, tags: ['base', 'aws'] }
    - { role: pyenv-pipenv, tags: ['base', 'python'] }
    - { role: npm-nvm, tags: ['base', 'node'] }
    - { role: redis, tags: ['base', 'db'] }
    - { role: postgresql, tags: ['base', 'db'] }
    - { role: docker, tags: ['base', 'container'] }
    - { role: poetry, tags: ['base', 'python'] }
    - { role: gcloud-cli, tags: ['base', 'cloud'] }
    - { role: packer, tags: ['base', 'infra'] }
    - { role: ml-training, tags: ['ml'] }
