---
  - name: Ensure required packages are installed
    dnf:
      name:
        - unzip
        - curl
      state: present
    become: true


  - name: Get latest Packer release version
    shell: >
      curl -s https://api.github.com/repos/hashicorp/packer/releases/latest |
      grep "tag_name" |
      cut -d '"' -f 4 | tr -d 'v'
    register: packer_version
    changed_when: false

  - name: Download Packer binary
    get_url:
      url: "https://releases.hashicorp.com/packer/{{ packer_version.stdout }}/packer_{{ packer_version.stdout }}_linux_amd64.zip"
      dest: "/tmp/packer.zip"

  - name: Unzip Packer binary
    unarchive:
      src: "/tmp/packer.zip"
      dest: "/usr/local/bin/"
      remote_src: yes
    become: true

  - name: Set executable permissions for Packer
    file:
      path: "/usr/local/bin/packer"
      mode: "0755"

  - name: Verify Packer installation
    command: "packer --version"
    register: packer_check
    changed_when: false

  - name: Debug Packer version
    debug:
      msg: "Packer installed successfully. Version: {{ packer_check.stdout }}"
