---
- name: Get current username
  command: whoami
  register: current_user
  changed_when: false

- name: Check if Docker is already installed
  command: docker --version
  register: docker_check
  ignore_errors: true
  changed_when: false

- name: Check if Docker Compose is already installed
  command: docker compose version
  register: docker_compose_check
  ignore_errors: true
  changed_when: false

- name: Install Docker and dependencies
  block:
    - name: Remove potential conflicting packages
      dnf:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent
      become: true

    - name: Add Docker repository
      get_url:
        url: https://download.docker.com/linux/fedora/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: true

    - name: Install Docker packages
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
      become: true
  when: docker_check.rc != 0

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: true
  become: true

- name: Check if user is already in docker group
  command: groups {{ current_user.stdout }}
  register: user_groups
  changed_when: false

- name: Create docker group
  group:
    name: docker
    state: present
  become: true
  when: '"docker" not in user_groups.stdout'

- name: Add user to docker group
  user:
    name: "{{ current_user.stdout }}"
    groups: docker
    append: yes
  become: true
  when: '"docker" not in user_groups.stdout'

- name: Install docker-compose via dnf
  dnf:
    name: docker-compose
    state: present
  become: true
  when: docker_compose_check.rc != 0

- name: Display Docker version
  debug:
    msg: "Docker installed successfully. You may need to log out and back in for group changes to take effect."
  when: docker_check.rc == 0
