---
  - name: Add Google Cloud repo
    yum_repository:
      name: google-cloud-sdk
      description: Google Cloud SDK repository
      baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64
      enabled: true
      gpgcheck: true
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    become: true

  - name: Install Google Cloud CLI
    dnf:
      name: google-cloud-sdk
      state: present
    become: true

  - name: Create GCloud config directory
    file:
      path: "{{ ansible_user_dir }}/.config/gcloud"
      state: directory
      mode: '0700'
    become: false
