#!/bin/bash

set -e


# Function to check if Python is installed (pyenv or otherise)
check_python() {
    if command -v python3 &>/dev/null; then
        PYTHON_VERSION=$(python3 --version 2>&1)
        echo "Python is installed: $PYTHON_VERSION"
    else
        echo "Python is not installed."
        install_python
    fi
}

# Function to install Python 3.11.0 globally on Fedora
install_python() {
    echo "Installing Python 3.11.0..."

    # Update the package repository
    sudo dnf -y update

    # Enable the Fedora Modular repository
    sudo dnf module reset python
    sudo dnf module enable python:3.11

    # Install Python 3.11
    sudo dnf install -y python3.11

    # Verify the installation
    if command -v python3.11 &>/dev/null; then
        echo "Python 3.11.0 has been installed successfully."
    else
        echo "Failed to install Python 3.11.0."
    fi
}

# Check if Python is installed and version
check_python

# Check if ansible is installed
setup_ansible () {

    if ! command -v ansible &> /dev/null
    then
        echo "Ansible is not installed. Installing Ansible..."

        # Update system packages
        sudo dnf update -y

        # Install Ansible
        sudo dnf install ansible -y

        echo "Ansible installed successfully!"
    else
        echo 'ansible is installed.'
        ansible --version
    fi
}

setup_ansible
