#!/bin/bash

set -e

# Prompt the user for AWS credentials
read -p "Enter your AWS Access Key ID: " AWS_ACCESS_KEY_ID
read -sp "Enter your AWS Secret Access Key: " AWS_SECRET_ACCESS_KEY
read -p "Enter your AWS Default Region: " AWS_DEFAULT_REGION
read -p "Enter your AWS Default Output: " AWS_DEFAULT_OUTPUT

# Export AWS credentials as environment variables
export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY
export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:"us-east-1"}
export AWS_DEFAULT_OUTPUT=${AWS_DEFAULT_OUTPUT:"json"}

# Check if ansible is installed
setup_ansible () {

    if ! command -v ansible &> /dev/null
    then
        echo "Ansible is not installed. Installing Ansible..."

        # Update system packages
        sudo dnf update -y

        # Install Ansible
        sudo dnf install ansible -y

        echo "Ansible installed successfully!"
    else
        echo 'ansible is installed.'
        ansible --version
    fi
}

setup_ansible
