---
  - name: Check if pyenv directory exists
    stat:
      path: "{{ ansible_env.HOME }}/.pyenv"
    register: pyenv_status
    ignore_errors: yes

  - name: Check if Python 3.11.10 is installed via pyenv
    shell: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv versions --bare | grep 3.11.10"
    register: python_version_status
    environment:
      PATH: "{{ ansible_env.HOME }}/.pyenv/bin:{{ ansible_env.HOME }}/.pyenv/shims:{{ ansible_env.PATH }}"
    when: pyenv_status.stat.exists
    changed_when: false
    failed_when: false
    ignore_errors: true


  - when: not pyenv_status.stat.exists or not python_version_status.stdout
    block:
      - name: Install Fedora dependencies
        become: yes
        dnf:
          name:
            - gcc
            - zlib-devel
            - bzip2
            - bzip2-devel
            - readline-devel
            - sqlite
            - sqlite-devel
            - openssl-devel
            - tk-devel
            - libffi-devel
            - xz-devel
            - git
            - curl
            - wget
            - make
          state: present

      # Install pyenv by running the shell script if not already installed
      - name: Install pyenv
        shell: curl https://pyenv.run | bash
        args:
          executable: /bin/bash

      - name: Add pyenv configuration to .bashrc
        lineinfile:
          path: "{{ ansible_env.HOME }}/.bashrc"
          line: |
            export PATH="$HOME/.pyenv/bin:$PATH"
            eval "$(pyenv init --path)"
            eval "$(pyenv init -)"
            eval "$(pyenv virtualenv-init -)"
          create: yes
          insertafter: EOF

      #if pyenv is installed and Python 3.11 is not
      - name: Install Python 3.11 using pyenv
        shell: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv install 3.11.10 && {{ ansible_env.HOME }}/.pyenv/bin/pyenv global 3.11.10"
        environment:
          PATH: "{{ ansible_env.HOME }}/.pyenv/bin:{{ ansible_env.HOME }}/.pyenv/shims:{{ ansible_env.PATH }}"
        args:
          executable: /bin/bash

      - name: Install pipenv using pip
        pip:
          name: pipenv
          executable: "{{ ansible_env.HOME }}/.pyenv/shims/pip"
