---
# Install Fedora dependencies
- name: Install system dependencies
  become: yes
  dnf:
    name:
      - gcc
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - xz-devel
      - git
      - curl
      - wget
      - make
    state: present

# Check if pyenv directory exists
- name: Check if pyenv directory exists
  stat:
    path: /root/.pyenv
  register: pyenv_status

# Check if Python 3.11 is installed via pyenv
- name: Check if Python 3.11.10 is installed via pyenv
  shell: |
    source ~/.bashrc
    pyenv versions --bare | grep 3.11.10
  register: python_version_status
  when: pyenv_status.stat.exists
  changed_when: false
  failed_when: false

# Install pyenv by running the shell script if not already installed
- name: Install pyenv
  shell: curl https://pyenv.run | bash
  args:
    executable: /bin/bash
  when: not pyenv_status.stat.exists

# Configure pyenv in .bashrc if pyenv was installed
- name: Add pyenv configuration to .bashrc
  lineinfile:
    path: ~/.bashrc
    line: |
      export PATH="$HOME/.pyenv/bin:$PATH"
      eval "$(pyenv init --path)"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
    create: yes
  when: not pyenv_status.stat.exists

# Reload bash to apply pyenv changes if pyenv was installed
- name: Source .bashrc to apply pyenv changes
  shell: source ~/.bashrc
  when: not pyenv_status.stat.exists

# Install Python 3.11 using pyenv if pyenv is installed and Python 3.11 is not installed
- name: Install Python 3.11 using pyenv
  shell: |
    source ~/.bashrc
    pyenv install 3.11.10
    pyenv global 3.11.10
    pyenv exec python -m ensurepip
  args:
    executable: /bin/bash
  when: pyenv_status.stat.exists and python_version_status.stdout == ""

# Install pipenv using pip
- name: Install pipenv
  pip:
    name: pipenv
    executable: "{{ ansible_env.HOME }}/.pyenv/shims/pip"
  when: pyenv_status.stat.exists or (ansible_env.HOME + '/.pyenv' in lookup('pipe', 'echo $PATH'))
